wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.19
    cli_version: 0.23.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1763752878
    t:
      1:
      - 12
      - 45
      - 50
      2:
      - 12
      - 45
      - 50
      3:
      - 4
      - 16
      - 42
      4: 3.10.19
      5: 0.23.0
      13: linux-x86_64
    e:
      d9icjera4fkpoaml7hqafwaye3xfslxo:
        os: Linux-5.14.0-570.58.1.el9_6.x86_64-x86_64-with-glibc2.34
        python: CPython 3.10.19
        started_at: '2025-11-21T19:21:16.931499Z'
        program: /rwthfs/rz/cluster/work/llg28990/aorpo/train.py
        code_path: train.py
        code_path_local: train.py
        git:
          remote_url: git@github.com:AachenTian/aorpo.git
          commit: fd1cc7eb747d83c81f54a1ad393c0dbb815db46b
        root: /rwthfs/rz/cluster/work/llg28990/aorpo
        host: n23g0017.hpc.itc.rwth-aachen.de
        executable: /home/llg28990/miniconda3/envs/aorpo_jax/bin/python
        cpu_count: 96
        cpu_count_logical: 96
        gpu_type: NVIDIA H100
        gpu_count: 1
        disk:
          /:
            total: '52361691136'
            used: '16141893632'
        memory:
          total: '540133511168'
        gpu_nvidia:
        - name: NVIDIA H100
          memory_total: '100485038080'
          cuda_cores: 16896
          architecture: Hopper
          uuid: GPU-a67fa617-9a56-05cd-f948-8cf8eccbb2bf
        cuda_version: '12.8'
        slurm:
          submit_dir: /rwthfs/rz/cluster/work/llg28990/aorpo
          tasks_per_node: '1'
          gtids: '0'
          job_partition: c23g
          submit_host: login23-1.hpc.itc.rwth-aachen.de
          nodelist: n23g0017
          job_account: p0021919
          job_uid: '52175'
          cpus_on_node: '1'
          node_aliases: (null)
          working_cluster: rcc:wlm23-1:6750:9728:109
          job_id: '62578139'
          nodeid: '0'
          job_cpus_per_node: '1'
          job_gpus: '0'
          export_env: NONE
          script_context: prolog_task
          job_gid: '52175'
          job_num_nodes: '1'
          task_pid: '144765'
          constraint: Rocky9
          job_nodelist: n23g0017
          get_user_env: '1'
          job_user: llg28990
          gpus_on_node: '1'
          cluster_name: rcc
          prio_process: '0'
          job_qos: normal
          mem_per_cpu: '5200'
          localid: '0'
          topology_addr_pattern: switch.switch.node
          procid: '0'
          conf: /etc/slurm/slurm.conf
          jobid: '62578139'
          job_name: aorpo_single
          nnodes: '1'
          topology_addr: spines1234.ibsw09.n23g0017
        writer_id: d9icjera4fkpoaml7hqafwaye3xfslxo
learning_rate:
  desc: null
  value: 0.0003
architecture:
  desc: null
  value: AORPO
Environment:
  desc: null
  value: mpe_spread_v3
epochs:
  desc: null
  value: 200
