wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.19
    cli_version: 0.23.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1763672082
    t:
      1:
      - 12
      - 45
      - 50
      2:
      - 12
      - 45
      - 50
      3:
      - 2
      - 4
      - 16
      - 42
      4: 3.10.19
      5: 0.23.0
      13: linux-x86_64
    e:
      hv3253ne3a1su4e4symdgcp9ecsnj8s3:
        os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
        python: CPython 3.10.19
        started_at: '2025-11-20T20:54:42.628093Z'
        program: /home/yachen/RL_projects/aorpo/train.py
        code_path: train.py
        code_path_local: train.py
        git:
          remote_url: git@github.com:AachenTian/aorpo.git
          commit: fd1cc7eb747d83c81f54a1ad393c0dbb815db46b
        root: /home/yachen/RL_projects/aorpo
        host: yachen-B550-VH-B
        executable: /home/yachen/anaconda3/envs/aorpo_jax/bin/python
        cpu_count: 8
        cpu_count_logical: 16
        gpu_type: NVIDIA GeForce RTX 4060
        gpu_count: 1
        disk:
          /:
            total: '48891670528'
            used: '14765166592'
        memory:
          total: '33588318208'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 4060
          memory_total: '8585740288'
          cuda_cores: 3072
          architecture: Ada
          uuid: GPU-711a23df-4281-3e27-db6b-a2b9bfef543a
        cuda_version: '12.8'
        writer_id: hv3253ne3a1su4e4symdgcp9ecsnj8s3
learning_rate:
  desc: null
  value: 0.0003
architecture:
  desc: null
  value: AORPO
Environment:
  desc: null
  value: mpe_spread_v3
epochs:
  desc: null
  value: 200
